// const express = require('express')
// const router = express.Router()
// //const AdminUserCheckAuth = require('../middleware/adminuser-check-auth')
// const CategoryController = require('../controllers/category')
// const MakeRequest = require('../middleware/make-request')
// const moment = require('moment')
// const multer = require('multer')
// const fs = require('fs')

// router.post('/', MakeRequest, CategoryController.add)
// //router.get('/',MakeRequest, CategoryController.get)
